config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[new show index create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[create new]
  before_action :set_bookmark, only: %i[new]

  def new; end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.movie), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.new
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]
  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col md-6 offset lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a new bookmark to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment, placeholder: 'Enter the comment for the movie you choose' %>
        <%= f.association :movie %>
        <%= f.submit "Submit bookmark", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_movie.html.erb
<p>
  <strong>Title</strong>
  <%= movie.title %>
</p>

<p>
  <strong>Overview</strong>
  <%= movie.overview %>
</p>

<p>
  <strong>Rating</strong>
  <%= movie.rating %>
</p>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wallpaperaccess.com/full/6060694.jpg);">
  <div class="container">
    <h3>Save any kind of movies</h3>
    <div class= "col text-center">
      <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

<div class="card-category">
    <h3 class= "mb-0"> My Lists </h3>
</div>

<div class="cards">
  <% @lists.each do |list| %>
    <%= link_to list_path(list), class: "text-decoration-none" do %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://wallpaperaccess.com/full/2000048.jpg)" >
        <div class= "text-center mt-5">
          <%= list.name %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class= "container py-5">
  <div class= "row">
    <div class="col-12 col md-6 offset lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for (@list) do |f| %>
        <%= f.input :name%>
        <%= f.submit  'Submit List', class: "btn btn-flat" %>
        <% end %>
        <%= link_to "Back", lists_path, class: "btn btn-primary position-end mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: url(https://wallpaperaccess.com/full/7180997.jpg)">
  <p><%= @list.name%></p>
</div>




<div class="movie-card">
  <div class="movie-card-info col-6 mt-5">
    <% @list.bookmarks.each do |bookmark| %>
    <div class= "bg-white rounded shadow h-100">
      <%= image_tag bookmark.movie.poster_url %>
      <div class= "p-3 rounded-bottom">
        <h2><%= bookmark.movie.title %></h2>
        <p><%= bookmark.movie.overview %></p>
        <div class= "d-flex justify-content-between">
          <p><i class="fas fa-quote-left me-2"></i><strong><%= bookmark.comment %></p></strong>
          <p>
            <%= link_to "Delete",
              bookmark_path(bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %>
          </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="text-right">
  <%= link_to "Back", lists_path, class: "btn btn-flat" %>
</div>